### ISSUE TITLE
Error if api.netatmo.net is not responding

### ISSUE THREAD

**Issue by rainerCH** [ssadams11/node-red-contrib-netatmo#4]
Hi!

node-red stops running if api.netatmo.net is not responding:

26 Jan 12:40:09 - Error: Authenticate error: No response
    at netatmo.handleRequestError (/home/pi/.node-red/node_modules/netatmo/netatmo.js:46:15)
    at netatmo.<anonymous> (/home/pi/.node-red/node_modules/netatmo/netatmo.js:115:19)
    at self.callback (/home/pi/.node-red/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/pi/.node-red/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

is it a problem of node-red-contrib-netatmo, or the netatmo module?

Cheers,
Rainer

**Comment by ssadams11** [comment]
I haven't had this error and we are using the contrib-netatmo nodes 24/7 without errors for months.  It might be a bug in your code if you are sending bad credentials.  I'd double check the strings you are entering in the config nodes and your code that forwards them to netatmo module API.  I'll close this issue as it doesn't seem to be in my module.
